### ISSUE TITLE
Need a way to execute code after every action

### ISSUE THREAD

**Issue by tv-brendan-jefferis** [brendan-jefferis/comp#4]
### Common scenario

1. Component A modifies it's internal model.
2. This changed data needs to be passed to another component

### Currrent solutions

**Option 1** Call `comp.components.componentB.refreshFoo(model.foo)` from all applicable Component A actions.

**Option 2** in Component A `init` function, listen for `comp_action` event on the component (or document), e.g.:

```
view() {
  init(actions, model) {
    var component = document.querySelector("[data-component=componentA]");
    component.addEventListener("comp_action", e => {
      comp.components.componentB.refreshFoo(model.foo);
    });
}
```

Neither of these solutions are that great.

**Option 1** forces repetition and increases risk of errors if the dev accidentally omits this Component B refresh call on an action.

**Option 2** is unintuitive and forces creation of additional event listeners, which would be a potential memory hog in a large, multi-component view (assuming they all used this pattern). This also turns the "workaround" `comp_actions` event - designed for easing integration with legacy systems - into a de facto addition to the core architecture.

## Proposal
Introduce a new view method called `prerender` which, as the name hopefully suggests, will be called immediately before a component's `render`. This would handle the above scenario like so:

```
view() {
  prerender(model) {
    comp.components.componentB.refresh(model.foo);
  },
  render(model, html) {
    return html`<div></div>`;
  }
}
```

**Comment by brendan-jefferis** [comment]
Package no longer supported
