### ISSUE TITLE
Event should always be fired on the element with the data-[event] attr

### ISSUE THREAD

**Issue by tv-brendan-jefferis** [brendan-jefferis/comp#5]
In the following case, the event target will be the `span`, when it should be the `button` - because that is where the `data-click` was specified

```
<button type="button" data-click="setFoo()" data-foo="1"><span>Click me</span></button>
```

**Comment by brendan-jefferis** [comment]
Project no longer supported

**Comment by brendan-jefferis** [comment]
Package no longer supported
